baseurl = "https://lgbouma.com/"
title = "home"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "" #"© 2019 — Some Author — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  #[[menu.main]]
  #  url = "/posts/"
  #  name = "blog"
  #  weight = 1
  [[menu.main]]
    url = "/bio/"
    name = "bio"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3
  [[menu.main]]
    url = "/research/"
    name = "research"
    weight = 3
  #[[menu.main]]
  #  url = "/oddities/"
  #  name = "oddities"
  #  weight = 3
  [[menu.main]]
    url = "/links/"
    name = "links"
    weight = 4


  # # Footer
  [[menu.footer]]
    url = "https://github.com/lgbouma"
    name = "github"
    weight = 1
  [[menu.footer]]
    url = "https://ui.adsabs.harvard.edu/public-libraries/uXPWdyI2RH2T-Sv0rcwUwA" 
    name = "publications"
    weight = 2
  [[menu.footer]]
    url = "https://lgbouma.com/pdfs/LukeBouma_CV_Spring2025.pdf" 
    name = "cv"
    weight = 3 
  [[menu.footer]]
    url = "https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AJsN-F7g3-jB3BwkL8d3mP_n5CJbMutUQQUzIe3I9EpGI3fXSURl3Vv1aBv53crsYXSUFuflj24kIXe02NTGjIkIHzNPrtz1NWQ4YlndGJbvhQUOfCjZ_po&user=RILfQ1EAAAAJ"
    name = "scholar"
    weight = 4
  [[menu.footer]]
    url = "/notes/"
    name = "notes"
    weight = 5
  [[menu.footer]]
    url = "/oddities/"
    name = "oddities"
    weight = 6

  # [[menu.footer]]
  #   url = "/posts/index.xml"
  #   name = "RSS"
  #   weight = 2
  # [[menu.footer]]
  #   url = "mailto:foo@bar.com"
  #   name = "Contact"
  #   weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
