baseurl = "https://lgbouma.com/"
title = "lgbouma"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "" #"© 2019 — Some Author — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  #[[menu.main]]
  #  url = "/posts/"
  #  name = "blog"
  #  weight = 1
  [[menu.main]]
    url = "/bio/"
    name = "bio"
    weight = 2
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3
  #[[menu.main]]
  #  url = "/oddities/"
  #  name = "oddities"
  #  weight = 3


  # # Footer
  [[menu.footer]]
    url = "https://github.com/lgbouma"
    name = "github"
    weight = 1
  [[menu.footer]]
    url = "https://ui.adsabs.harvard.edu/search/filter_database_fq_database=OR&filter_database_fq_database=database%3A%22astronomy%22&fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=(database%3A%22astronomy%22)&q=author%3A(%22bouma%2C%20l%22)&sort=date%20desc%2C%20bibcode%20desc"
    name = "publications"
    weight = 2
  [[menu.footer]]
    url = "/notes/"
    name = "notes"
    weight = 3
  [[menu.footer]]
    url = "/oddities/"
    name = "oddities"
    weight = 3
  # [[menu.footer]]
  #   url = "/posts/index.xml"
  #   name = "RSS"
  #   weight = 2
  # [[menu.footer]]
  #   url = "mailto:foo@bar.com"
  #   name = "Contact"
  #   weight = 3


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
